version: "3"

services:
   app:
      build:
        context: .
      ports:
      - "5000:5000"
      volumes:
      - .:/app
      environment:
        - SECRET_KEY=secretkey
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_NAME=simporter_data
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=password
      command: >
        sh -c "
            python manage.py db init     &&
            python manage.py db migrate  &&
            python manage.py db upgrade  &&
            python manage.py populate data.csv &&
            python manage.py runserver  --host 0.0.0.0"
      depends_on:
        - db

   db:
      image: postgres:10-alpine
      environment:
        - POSTGRES_DB=simporter_data
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password